= thesauron(1)
krebs
:doctype: manpage
:manmanual: krebs Manuals

== Name

thesauron - the krebs thesaurus

== Definitions

Cholerab n. [de]::
* Kunstwort aus Kollaboration und Cholera. Beschreibt den Zustand, dass
Zusammenarbeit niemals gut, einfach und ohne Schmerzen funktioniert.
* Teamwork-Plattform für Krebscode.

[[eigentlich]] eigentlich adv. [de]::
Hinweis darauf, dass der Inhalt eines Satzes eine Soll-Realität
beschreibt, die nicht der Fall ist. +
Antonym: <<tatsaechlich>>

[[ghost]] ghost n. [de]::
Host im Darknet welcher evtl. irgendwie noch da ist (als dd image auf
anderen Festplatten) aber wohl nie wieder kommen wird. +
Siehe: <<Wiederbelebung>>


KD;RP abbr. /ˈkaːdeʁp/ [en]::
Short for Krebs Darknet / Retiolum Prefix.

krebs [de]::
krebs ist ein soziales Experiment, eine Organisation, das zweitälteste Softwareprojekt im Shack und viel verteilte infrastruktur.

kremium [en]::
coinage derived from the words premium and krebs +
see: broken +
usage: Reaktor ircbot has unfixed broken behavior since ever -> "Kremium Software"

KRI abbr. /kɹaɪ̯/ [en]::
Short for Krebs Request for Implementation. +
Derived from Scheme Requests for Implementation (SRFI).

litterate programming n. [en]::
any code that has not been proved mathematically.

Nahziel n. [de]::
Ziel mit höchst möglicher Priorität.

Nahzielerfahrung n. [de]::
das Erlebnis der (endgültigen) Nichterreichung eines Nahziels (obwohl
nur noch wenig \((quasi-) infinitesimal viel) nötig gewesen wäre).

parentheses of fear [en]::
unnecessary parentheses, usually used when order of precedence is unknown. +

.parentheses of fear
====
`1 + (2 * 3)`
====

[[Protip]] Protip n. [en]::
(Probably vague) description how a task can be solved. +
Antonym: <<Spoiler>> +

.Protip
====
* To defeat the Cyberdaemon, shoot at it until it dies.
* RTFM
====

Punching Lemma n. [de]::
Sozialer Druck zur Aufrechterhaltung der Ordnung in dem sozialen
Geflecht von Krebs

ref n. [en]::
A reference like an URI, ISBN, name of a person, etc.

reftrace n. [en]::
A stacktrace-like representation of refs that lead to some (any kind
of) conclusion. Usually generated by a human. The conclusion can be
either on the top or on the bottom of the stack. If the order is
ambiguous, then it should be communicated explicitly. +

.reftrace (conclusion first)
====
* http://en.wikipedia.org/wiki/Stacktrace
* google "stacktrace" (first entry / 2014-12-05T12:13:58Z)
* think about some example [this could be omitted, as it’s obvious…]
====

Retiolum n. [en]::
The official darknet of Krebs which utilizes the Retiolum Prefix to
address individual nodes.

Retiolum Prefix n. [en]::
The universally accepted IPv6-prefix, 42::/16. Anyone can has a
/128-subnet and, if require, anything larger.

Retiolum Realtime Map n. [en]::
The network map of the public visible part of Retiolum.

RRM abbr. [en]::
Short for Retiolum Retiolum Map.

Sanatorium n. [en]::
The Krebs Control and Command Center.
An Retiolum-based IRC-channel where all Reaktor-enabled nodes gather
and lurk for relevant input. +
De facto: `#xxx`

[[Spoiler]] Spoiler n. [en]::
A subset of walkthrough, i.e. any individual steps may be omitted. +
Antonym: <<Protip>>


Super Effect n. [en]::
An effect on top of the desired / planned effect(s).  +

.Super Effect
====
* Software bugs / vulnerabilities
* "Aargh! My shell code isn't properly escaped and deletes `/`"
====

super effective adj. [en]::
Something that posseses one or more super effects.

[[tatsaechlich]] tatsächlich adv. [de]::
Hinweis darauf, dass der Inhalt eines Satzes exakt der Realität
entspricht. +
Antonym: <<eigentlich>>

Verkrebsung n. [de]::
Synonym für die Installation von Krebs (oder eine einzelnen Krebs
Komponente) auf einem beliebigem System.

Walkthrough n. [en]::
Description of the individual steps to complete a task. +

.Walkthrough
====
* program code
* small-step semantics
====

[[Wiederbelebung]] Wiederbelebung n. [de]::
Ein ghost wird im Darknet wieder erreichbar +
Siehe: <<ghost>>

== See also

enterprise-patterns(1)
